### PR TITLE
added stopListening method

### PR DESCRIPTION
**Pull request by mahdidahouei**
This plugin had a bug that when we close the application it used to throw an error saying that sms_receiver has leaked a listener...
so I implemented`stopListening` method to it. now it should be called in `dispose` method.

### CODE REVIEW

**Comment by iqbalmineraltown** [comment]
Thanks! Looks good to me

could you update the example project and provide how-to-use in README?

**Comment by dnordberg** [comment]
Could you please merge this and update the version, doesn't seem I can use your package otherwise since it keeps looking for SMS messages if the listener is not disposed and you enter the code manually.

**Comment by iqbalmineraltown** [comment]
I'd love to merge this after example usage and readme provided

**Comment by iqbalmineraltown** [comment]
thanks for your PR 😄 
I've just implemented this on 0.4.0, feel free to open PR for further improvements

**Pull request closed without merging**
